-- Disable RLS on all tables for development
-- TODO: Enable RLS with proper policies before production launch

ALTER TABLE "Account" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "User" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Clinic" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Doctor" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Staff" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Service" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceDoctor" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Patient" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Appointment" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "SoapNote" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Invoice" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Conversation" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Message" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "FeatureFlag" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "EventBus" DISABLE ROW LEVEL SECURITY;
